### ISSUE TITLE
Actually show how to use the library?

### ISSUE THREAD

**Issue by eljobe** [gradle-guides/building-java-libraries#10]
![image](https://cloud.githubusercontent.com/assets/679924/26661620/c26e9820-46b9-11e7-9412-b1fc88b19be4.png)

This part of the guide promises that we will use the library in some application code, but then we don't deliver on that promise in this guide.

We should either:
Deliver on the promise
or
Remove the promise

This is also mentioned in the summary section of the guide which is misleading there as well.
![image](https://cloud.githubusercontent.com/assets/679924/26661674/0d80af60-46ba-11e7-8aca-c7ce2da97253.png)

**Comment by lacasseio** [comment]
Issue moved to [gradle/guides #209](https://github.com/gradle/guides/issues/209) via [**ZenHub**](https://www.zenhub.com/)
