### ISSUE TITLE
Cleanup Summary Bullet List

### ISSUE THREAD

**Issue by eljobe** [gradle-guides/building-java-libraries#11]
On this part of the guide:
![image](https://cloud.githubusercontent.com/assets/679924/26661728/779a1346-46ba-11e7-885d-ddc4b35ff166.png)

There are a few issues. The bullet list is introduced with "Along the way, you’ve learned how to:", but then "How to" is repeated in two of the bullets of the list. Also, the 5th bullet wouldn't smoothly flow as something we've learned how to do.

I suggest:
1. rewording the second bullet to fit the flow after "how to:"
2. dropping "How to:" from the first and third items.
3. rewording the 5th item to fit the flow.
4. dropping the period at the end of the 5th item or adding it to the first 4.
5. (Optional) lowercasing the initial word in each item.

Like this:

Along the way, you've learned how to:
- generate a Java library.
- adapt the build file and Java files generated by `gradle init`.
- run the build and view the test report.
- customize the name of a JAR file and the content of its manifest.
- generate API documentation.

**Comment by ysb33r** [comment]
Fixed.
