### ISSUE TITLE
This guide uses "build file" which is agains the Style Guide

### ISSUE THREAD

**Issue by eljobe** [gradle-guides/building-java-libraries#13]
According to the style guide, we should [prefer "build script" over "build file"](https://github.com/gradle-guides/style-guide#favor-build-script-over-build-file) for consistency within our guides. This guide runs afoul of that suggestion two or three times (depending on whether or not you think it's okay to say "`build.gradle` file" instead of "`build.gradle` script")

**Comment by ysb33r** [comment]
Fixed.
