### ISSUE TITLE
Wrong generated code

### ISSUE THREAD

**Issue by figaw** [gradle-guides/building-java-libraries#16]
In [Review the generated project files](https://guides.gradle.org/building-java-libraries/#review_the_generated_project_files), the following

```
version = '0.1.0'

jar {
    manifest {
        attributes('Implementation-Title': project.name,
                   'Implementation-Version': project.version)
    }
}
```

is not generated automatically.

It might confuse new users as to whether they should be adding it in this step in the tutorial - also because it changes the name of the generated jar-file, and it's [explicitly stated in this step](https://guides.gradle.org/building-java-libraries/#customize_the_library_jar) that they should make changes, and note this difference.

So it should probably be removed in this step

(I would've removed it in a pull request, but I seem unable to find the files generating the documentation. Missing?)

**Comment by lacasseio** [comment]
Issue moved to [gradle/guides #224](https://github.com/gradle/guides/issues/224) via [**ZenHub**](https://www.zenhub.com/)
