### ISSUE TITLE
No Information about how to get the dependencies of the library

### ISSUE THREAD

**Issue by alexanderveit** [gradle-guides/building-java-libraries#17]
`gradle build` places the generated library in the `lib` directory of the project.

However, the dependencies declared in `build.gradle` are also needed to deploy the library in the runtime environment. The doc does not describe how to achieve this.

**Comment by lacasseio** [comment]
Issue moved to [gradle/guides #225](https://github.com/gradle/guides/issues/225) via [**ZenHub**](https://www.zenhub.com/)
