### ISSUE TITLE
Rename to "Building Java libraries"

### ISSUE THREAD

**Issue by pioterj** [gradle-guides/building-java-libraries#2]
I think we should rename this guide to "Building **Java** libraries". This is what this guide is really about. I'd cover Groovy, Scala and possibly other JVM languages in separate guides.

**Comment by ysb33r** [comment]
We need to coordinate the name change with a change on the dotorg-site. Will need to have @chaficnajjar or @eriwen to sit with me on a call and if I do the guides part, they'll need to activate the dotorg-site and add a Cloudflare redirect.

**Comment by chaficnajjar** [comment]
I'll take care of this tomorrow with you @ysb33r. Just ping me :+1:

**Comment by ysb33r** [comment]
Nice work there @chaficnajjar. Working on the call together made it a seamless change.

**Comment by ysb33r** [comment]
I'm closing this one out.
