### ISSUE TITLE
gradle init prompts for build script DSL

### ISSUE THREAD

**Issue by glennoph** [gradle-guides/building-java-libraries#24]
Executing the following command from gradle 5.1 : 
```
gradle init --type java-library --project-name jvm-library
```
Prompts for build script DSL: 
```
Select build script DSL:
  1: groovy
  2: kotlin
```

This was unexpected from the getting started guide.

**Comment by das-g** [comment]
This probably depends on the exact Gradle version. See also gradle-guides/building-java-applications#16

**Comment by lacasseio** [comment]
Issue moved to [gradle/guides #265](https://github.com/gradle/guides/issues/265) via [**ZenHub**](https://www.zenhub.com/)
