### ISSUE TITLE
Incorrect value for rootProject.name

### ISSUE THREAD

**Issue by sannidhi01** [gradle-guides/building-java-libraries#25]
Under [Review the generated project files](https://guides.gradle.org/building-java-libraries/#review_the_generated_project_files) , value for rootProject.name is 'building-java-libraries' which must be 'jvm-library' as it was passed as a value to the init task, earlier, in 'Run the init task' section.

**Comment by lacasseio** [comment]
All other guides set the `rootProject.name` to the guide repo name. I made the change to keep align with the other guides. Thanks for the catch.
