### ISSUE TITLE
It is not clear where to add version property in build script

### ISSUE THREAD

**Issue by mvsagar** [gradle-guides/building-java-libraries#26]
A minor issue that may bother developers new to Groovy.
Section "Customize the Library JAR" (https://guides.gradle.org/building-java-libraries/#customize_the_library_jar) of the Gradle user manual says version property should be set at top-level in build script build.gradle. But it is not clear where in the build script the property should be set!  In absence of the specific information on location in the script for adding the version property, developers without any familiarity with Groovy may not be able to test the feature. Build failed when I added the entry at the beginning of the build script but passed when I added at the end of the script. It would be nice if the second sentence of first paragraph of the section is changed from
"This is easily achieved by setting a top-level version property in the build script, like so:" to
"This is easily achieved by setting a top-level version property at the end in the build script as following:" or in some other appropriate way.

**Comment by leforestier** [comment]
I'm here because my build failed at this step of the tutorial as well. It would be nice to be able to see the full build.gradle file in the tutorial. I would also be interested in knowing why it works if you add the version number at the end of the file but not if you add it at the beginning.

**Comment by AlexErP** [comment]
* setting a top-level version property in the build script
This is not correct. In this case we are faced with error: 

> only buildscript {} and other plugins {} script blocks are allowed before plugins {} blocks, no other statements are allowed

but if set _version_ after **plugins**  define it'll be ok

**Comment by lacasseio** [comment]
Issue moved to [gradle/guides #269](https://github.com/gradle/guides/issues/269) via [**ZenHub**](https://www.zenhub.com/)
