### ISSUE TITLE
Use init plugin to create the library

### ISSUE THREAD

**Issue by pioterj** [gradle-guides/building-java-libraries#3]
This is what we do in other guides:
- https://guides.gradle.org/creating-new-gradle-builds/
- https://guides.gradle.org/creating-java-applications/

**Comment by ysb33r** [comment]
Ah! Just tried it with `3.4.1` and it works.

**Comment by ysb33r** [comment]
@kousen This is ready for review. I had to remove a lot of your original content to keep in in the same structure as the `building-(groovy|scala)-libraries` guides. However I kept as much as I could. Therefore this has more bits that the other two guides, but I think these extra bits are useful in Java context and do not need repeating in the other two guides. This a

To review you will need to checkout the `use-init-plugin` branch.

**Comment by kousen** [comment]
Quick comment: after cloning the repo again (to make sure I started fresh), I can't resolve any of your implied file and directory links, like `{initlogfile}, `{initexampledir}`, or `{doclogfile}`. Are they generated as part of a Gradle task you added?

Btw, I fixed a couple of typos and changed the word `Spock` to `JUnit` :), all on the `use-init-plugin` branch.
