### ISSUE TITLE
Remove "Consume the library JAR" section

### ISSUE THREAD

**Issue by pioterj** [gradle-guides/building-java-libraries#4]
I think the [Consume the library JAR](https://guides.gradle.org/building-jvm-libraries/#consume_the_library_jar) section belongs to a separate guide on [consuming JVM libraries](https://github.com/gradle/guides/issues/6). I'd link to that guide as a next step instead of covering it here. Especially if we [rename it to building Java libraries](https://github.com/gradle-guides/building-jvm-libraries/issues/2) and create new guides for building [Groovy](https://github.com/gradle/guides/issues/76) and [Scala](https://github.com/gradle/guides/issues/77) libraries.

**Comment by ysb33r** [comment]
@kousen Also see #5. This work is on the same branch -> `add-javadoc`
