### ISSUE TITLE
Add section on Javadoc

### ISSUE THREAD

**Issue by pioterj** [gradle-guides/building-java-libraries#5]
Generating Javadoc is a common use case when building Java library. Together with separating consumption to a separate guide https://github.com/gradle-guides/building-jvm-libraries/issues/4 it should keep the guide roughly at the same size.

I'd also consider this for Groovy libraries https://github.com/gradle/guides/issues/76
and Scala libraries https://github.com/gradle/guides/issues/77 as the task and tool used to generate docs in all of those languages is different.

**Comment by ysb33r** [comment]
@kousen the Javadoc section has been added. (I would suggest reviewing this before looking at #3).

To review you would need to checkout the `add-jaavdoc` branch.

**Comment by kousen** [comment]
Again, I can't resolve `{codedir}`, though it's obviously `src/main`. I just don't see the setting for it.

The new JavaDoc section is really simple. My only issue is that I never knew the proper capitalization of `javadoc`. From what I can google, I think it's supposed to be all lowercase except when it's used at the beginning of a sentence. I updated the `index.adoc` file accordingly.
