### ISSUE TITLE
Brand new users might not understand Artifactory Bintray Repository

### ISSUE THREAD

**Issue by eljobe** [gradle-guides/building-java-libraries#7]
When an uninitiated user reads this:
![image](https://cloud.githubusercontent.com/assets/679924/26661365/337caa86-46b8-11e7-8385-327710ce42c6.png)

They may not know what we're talking about. Maybe add a hyperlink to jcenter, artifactory or bintray's website in the footnote?

**Comment by lacasseio** [comment]
Issue moved to [gradle/guides #208](https://github.com/gradle/guides/issues/208) via [**ZenHub**](https://www.zenhub.com/)
