### ISSUE TITLE
Reword congratulatory statement

### ISSUE THREAD

**Issue by eljobe** [gradle-guides/building-java-libraries#9]
The guide currently says:
"Congratulations, you have just completed the step from creating a Java library! You can can now customize this to your own project needs."

".. the step from creating a Java library!" comes off as very awkward to this native English speaker.

Replace that with one of:
"... creating a Java library!"
"... the first step of creating a Java library!"
"... the first step of this guide!"

**Comment by ysb33r** [comment]
Fixed
